### ISSUE TITLE
Has anyone gotten i18n to work with ng2 and JS API?

### ISSUE THREAD

**Issue by llam001** [tomwayson/angular2-esri-example#31] opened 2016-11-11 23:52 UTC
Was looking into [Angular's internationalization tool ng-xi18n](https://angular.io/docs/ts/latest/cookbook/i18n.html) but getting errors with the require statements.

> Error: Error encountered resolving symbol values statically. Calling function 'require', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.

Anyone have any experience getting i18n working with ng-xi18n or with any other tools?

**Comment by tomwayson** [comment] 2016-11-15 14:08
Are you able to share your code, or create minimal example based off [the i18n plunker](http://plnkr.co/edit/?p=preview) that demonstrates the error?

**Comment by kbedel** [comment] 2016-12-08 18:42
The cause of this issue was that we were loading the html templates into the components incorrectly. Changing to use the templateUrl property with the `angular2-template-loader` as recommended in the [Angular 2 Webpack doc](https://angular.io/docs/ts/latest/guide/webpack.html) resolved this.

**Comment by tomwayson** [comment] 2016-12-08 19:00
Thanks @kbedel - I added that link to the README.

@llam001 can we close this issue?

**Closed as completed** 2016-12-21 18:35 UTC
Labels: question
